services:
    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:4
        container_name: Lavalink
        restart: unless-stopped
        networks:
            - lavalink
        expose:
            - 2333
        ports:
            - '2333:2333'
        environment:
            - _JAVA_OPTIONS=-Xmx6G
        volumes:
            - ./lavalink/application.yml:/opt/Lavalink/application.yml

    bot:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: Discord-Bot-API
        env_file:
            - .env
        ports:
            - '8080:8080'
        expose:
            - 8080
        restart: unless-stopped
        networks:
            - lavalink

networks:
    lavalink:
        name: lavalink
